---
- name: Ensure /home/git/repos folder 
  ansible.builtin.file:
    path: /home/git/repos
    state: directory
    owner: git
    group: git
  become: yes
- name: Init repos 
  ansible.builtin.include_tasks: ./init_repo.yml
  loop: "{{ role_git__git_repos }}"
  loop_control:
    loop_var: repo_name
